# Generated by Django 5.1.4 on 2025-05-13 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBD_project', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
