# Generated by Django 5.1.4 on 2025-05-28 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('foto_url', models.URLField(blank=True, null=True)),
                ('contacto_dueno', models.CharField(max_length=255)),
                ('descripcion_campaña', models.TextField(blank=True, null=True)),
                ('min_inventario', models.IntegerField(default=0)),
                ('registro_final', models.BooleanField(default=False)),
                ('tareas_pendientes', models.IntegerField(default=0)),
                ('fecha_creacion_campaña', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campañas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
