# Generated by Django 5.1.4 on 2025-05-28 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBD_Campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='usuario',
        ),
        migrations.AddField(
            model_name='campaign',
            name='administrador',
            field=models.ForeignKey(default=2, limit_choices_to={'is_superuser': True}, on_delete=django.db.models.deletion.CASCADE, related_name='campañas_admin', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campañas_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='nombre_campaña',
            field=models.CharField(default='Sin Nombre', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='vendedores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_staff': True}, related_name='campañas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
