# Generated by Django 5.1.4 on 2025-05-28 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBD_Campaigns', '0002_remove_campaign_usuario_campaign_administrador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='activo', max_length=10)),
                ('nombre_campana', models.CharField(max_length=255)),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_campanas/')),
                ('contacto_dueno', models.CharField(max_length=255)),
                ('descripcion_campana', models.TextField(blank=True, null=True)),
                ('fecha_creacion_campana', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.ForeignKey(limit_choices_to={'is_superuser': True}, on_delete=django.db.models.deletion.CASCADE, related_name='campanas_admin', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas_cliente', to=settings.AUTH_USER_MODEL)),
                ('vendedores', models.ManyToManyField(blank=True, limit_choices_to={'is_staff': True}, related_name='campanas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoLive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_corto', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='archivos_lives/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_subidos', to=settings.AUTH_USER_MODEL)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_lives', to='OBD_Campaigns.campana')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=255)),
                ('desc_producto', models.TextField(blank=True, null=True)),
                ('cantidad_disponible', models.PositiveIntegerField(default=0)),
                ('cantidad_vendida', models.PositiveIntegerField(default=0)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_items/')),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='OBD_Campaigns.campana')),
            ],
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
    ]
