# Generated by Django 5.1.4 on 2025-06-06 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBD_Campaigns', '0003_campana_archivolive_item_delete_campaign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil_nombre', models.CharField(max_length=255)),
                ('perfil_url', models.URLField()),
                ('perfil_id', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
                ('texto', models.TextField()),
                ('fuente_url', models.URLField()),
                ('contado', models.BooleanField(default=False)),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OBD_Campaigns.campana')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='interactuar', help_text='Tipo de tarea (ej. responder, revisar)', max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('completado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('asignados', models.ManyToManyField(blank=True, limit_choices_to={'is_staff': True}, to=settings.AUTH_USER_MODEL)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='OBD_Campaigns.comentario')),
            ],
        ),
    ]
