# Generated by Django 5.1.4 on 2025-05-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBD_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('vendedor', 'Vendedor')], max_length=10),
        ),
    ]
